config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  resources :projects do
    resources :tasks do
      member do
        patch :completed
        patch :change_position
      end
    end
  end

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, -> { order(position: :asc) }, :dependent => :destroy
  validates :title,
            :presence => {:message => "can't be blank" }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  acts_as_list scope: :project
  scope :uncompleted, -> { where(completed: false) }
  scope :completed, -> { where(completed: true) }

  validates :name,
            :presence => {:message => "can't be blank." }
  validate :deadline_cannot_be_in_the_past

  def deadline_cannot_be_in_the_past
    if !deadline.blank? and deadline < Date.today
      errors.add(:deadline, "date can't be in the past")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)
    respond_to do |format|
      if @project.save
        format.json { render partial: 'project', status: :created, location: @project, locals: {project: @project} }
        format.js {}
      else
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.json { render partial: "project", status: :ok, location: @project, locals: {project: @project} }
        format.js {  }
      else
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    respond_to do |format|
    @project.destroy
      format.json { head :no_content }
      format.js {}
    end
  end

  private
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  respond_to :html, :json
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :json

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, except: [:create]

  def create
    @task = @project.tasks.create(task_params)
    respond_to do |format|
      if @task.save
        format.js {}
        format.json { render partial: "task", status: :ok, locals: {task: @task}, location: @task }
      else
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def completed
    respond_to do |format|
      if params[:completed] == "close"
        @task.update(completed: true) && @task.remove_from_list
        format.js {}
        format.json { render partial: "project", status: :ok, locals: {project: @project} }
      elsif params[:completed] == "open"
        @task.update(completed: false) && @task.insert_at(@project.tasks.uncompleted.count + 1)
        format.js {}
        format.json { render partial: "project", status: :ok, locals: {project: @project} }
      end
    end
  end

  def change_position
    respond_to do |format|
      if params[:direction] == "up"
        @task.move_higher
        format.js {}
        format.json { render partial: "project", status: :ok, locals: {project: @project} }
      elsif params[:direction] == "down"
        @task.move_lower
        format.js {}
        format.json { render partial: "project", status: :ok, locals: {project: @project} }
      end
    end
  end

  def destroy
    if @task.destroy
      flash[:success] = "Task was deleted."
      respond_to do |format|
          format.js {}
      end
    else
      flash[:error] = "Task could not be deleted."
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.js {}
        format.json { render partial: "task", data: {task_id: @task.id}, status: :ok, locals: {task: @task}, location: @task }
      else
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def get_last_position
    @last_position = @project.tasks.where.not(position: nil).last.position
  end

  def task_params
    params.require(:task).permit(:name, :deadline, :completed, :position)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  respond_to :html, :js

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
=begin
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
=end 
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
    <div class="modal-loader"></div>
  </body>
</html>

app/views/projects/_edit.slim
.modal.fade id="edit_project" role="dialog"
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" &times;
        h3 Edit project
      .modal-body
        == form_for @project, remote: true do |f|
          .form-group
            == f.label "Title:"
            == f.text_field :title, required: "true", class: "form-control", id: "title", autofocus: true
            == f.submit "Save changes", class: "btn btn-primary submit_form"

app/views/projects/_new.slim
.modal.fade id="create_project" role="dialog"
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" &times;
        h3 Create new project
      .modal-body
        == form_for(@project, remote: true) do |f|          
          .form-group
            == f.label "Title:"
            == f.text_field :title, required: "true", class: "form-control", id: "title", autofocus: true
            == f.submit "Create project", class: "btn btn-primary submit_form", data: { disable_with: "Please wait..."} 

app/views/projects/_project.slim
.project id="#{project.id}"
  .header
    .title
      i.fa.fa-list-alt aria-hidden="true"
      h3
        == project.title
    .options
      == link_to edit_project_path(project.id), :remote => true do 
        i.fa.fa-pencil
      == link_to project_path(project.id), class: "delete_project", remote: true, method: :delete, data: { confirm: 'Are you sure?'} do 
        i.fa.fa-trash      
  .task_form id="#{project.id}"
    == render partial: "tasks/form", locals: {project: project}    
  .tasks id="#{project.id}"
    == render project.tasks.all

app/views/projects/create.js.erb
var project = $("<%= escape_javascript(render @project) %>");
$('.modal#create_project').modal('hide');

$('h2').after(project)

app/views/projects/destroy.js.erb
$(".delete_project").on("ajax:complete", function(event,xhr,status){
  var project = $(event.currentTarget).parents('.project');
  project.remove();
});

app/views/projects/edit.js.erb
$('<%= j render "edit" %>').modal();

// Project title validation
$(document).on("ajax:error", function(e, data, status, xhr) {
  return $(".edit_project").render_form_errors('project', data.responseJSON);
});

$.fn.render_form_errors = function(model_name, errors) {
  var form;
  form = this;
  this.clear_form_errors();
  return $.each(errors, function(field, messages) {
    var input;
    input = form.find('input').filter(function() {
      var name;
      name = $(this).attr('name');
      if (name) {
        return name.match(new RegExp(model_name + '\\[' + field + '\\(?'));
      }
    });
    input.closest('.form-group').addClass('has-error');
    return input.after('<span class="help-block">' + $.map(messages, function(m) {
      return m.charAt(0).toUpperCase() + m.slice(1);
    }).join('<br />') + '</span>');
  });
};

$.fn.clear_form_errors = function() {
  this.find('.form-group').removeClass('has-error');
  return this.find('span.help-block').remove();
};

$.fn.clear_form_fields = function() {
  return this.find(':input', '#edit_project').not(':button, :submit, :reset, :hidden').val('').removeAttr('checked').removeAttr('selected');
};

app/views/projects/index.slim
- current_user.projects.order(created_at: :desc).each do |project|
  == render partial: 'projects/project', locals: {project: project}
        
div class="links"
  == link_to "New Project", new_project_path, :remote => true, class: "btn btn-primary btn-lg"

app/views/projects/new.js.erb
$('<%= j render "new" %>').modal();

// Project title validation
$(document).on("ajax:error", function(e, data, status, xhr) {
  return $(".new_project").render_form_errors('project', data.responseJSON);
});

$.fn.render_form_errors = function(model_name, errors) {
  var form;
  form = this;
  this.clear_form_errors();
  return $.each(errors, function(field, messages) {
    var input;
    input = form.find('input').filter(function() {
      var name;
      name = $(this).attr('name');
      if (name) {
        return name.match(new RegExp(model_name + '\\[' + field + '\\(?'));
      }
    });
    input.closest('.form-group').addClass('has-error');
    return input.after('<span class="help-block">' + $.map(messages, function(m) {
      return m.charAt(0).toUpperCase() + m.slice(1);
    }).join('<br />') + '</span>');
  });
};

$.fn.clear_form_errors = function() {
  this.find('.form-group').removeClass('has-error');
  return this.find('span.help-block').remove();
};

$.fn.clear_form_fields = function() {
  return this.find(':input', '#new_project').not(':button, :submit, :reset, :hidden').val('').removeAttr('checked').removeAttr('selected');
};

app/views/projects/update.js.erb
var project = $("<%= escape_javascript(render @project) %>");
$('.modal#edit_project').modal('hide');
$('.project#' + project[0].id).replaceWith(project);

app/views/shared/_sign_in.slim
.modal.fade id="sign_in" role="dialog"
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        button.close data-dismiss="modal" x
      h2 Sign in
      
      .modal-body
      == form_for(User.new, url: session_path(:user), 
                            html: {id: "sign_in_user"}, 
                            data: { type: 'json' }, 
                            format: :json, 
                            remote: true) do |f|
        .form-group
          == f.label "Email:"
          == f.email_field :email, autofocus: true, class: "form-control", id: "email"
        .group_input
          == f.label "Password:"
          == f.password_field :password, autocomplete: "off", class: "form-control", id: "pwd"
        == f.submit "Sign in", class: "btn btn-primary submit_form"
      .modal-footer

app/views/shared/_sign_up.slim
.modal.fade id="sign_up" role="dialog"
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        button.close data-dismiss="modal" x
      h2 Sign up    
      .modal-body
      == form_for(User.new, url: registration_path(:user),
                            html: {id: "sign_up_user"}, 
                            data: { type: 'json' }, 
                            format: :json,
                            remote: true) do |f|
        .form-group
          == f.label "Email:"
          == f.email_field :email, autofocus: true, class: "form-control", id: "email"
        .form-group
          == f.label "Password:"
          == f.password_field :password, autocomplete: "off", class: "form-control", id: "pwd"
        .form-group
          == f.label "Password confirmation:"
          == f.password_field :password_confirmation, autocomplete: "off", class: "form-control", id: "pwd"
        == f.submit "Sign up", class: "btn btn-primary submit_form"
      .modal-footer

app/views/tasks/_edit.slim
.modal.fade id="edit_task" role="dialog"
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" &times;
        h3 Edit task
      .modal-body
        == form_for @task, url: project_task_path, method: :patch, remote: true do |f|          
          .form-group
            == f.label "Name:"
            == f.text_field :name, required: "true", class: "form-control", id: "title", autofocus: true
            == f.label "Deadline"
            == f.text_field :deadline, class: "form-control datepicker"
            == f.submit "Save changes", class: "btn btn-primary submit_form edit_task"

app/views/tasks/_form.slim
== form_for([project, project.tasks.build], remote: true) do |f|
  i.fa.fa-plus
  == f.text_field :name, required: "true", placeholder: "Start typing here to create a task…"
  == f.submit "Add Task", class: "btn btn-success add_new_task", data: { disable_with: "Wait..."}

app/views/tasks/_task.slim
- unless task.new_record?
  - if task.completed == false
    .task class="active" id="#{task.id}"  
      .checkbox
        == check_box_tag("data", value = "#{task.project_id}", checked = false, class: 'task-check', id: task.id)
      .info
        - if task.deadline.nil?
          == task.name
        - else
          == task.name
          span #{task.deadline.strftime('%a, %m/%d/%y')}
      .options  
        == link_to change_position_project_task_path(id: task.id, project_id: task.project_id, direction: 'up'), remote: true, method: :PATCH do
            i.fa.fa-caret-up
        == link_to change_position_project_task_path(id: task.id, project_id: task.project_id, direction: 'down'), remote: true, method: :PATCH do
            i.fa.fa-caret-down
        == link_to edit_project_task_path(task.project_id, task.id), class: "edit_task", remote: true do
            i.fa.fa-pencil
        == link_to project_task_path(task.project_id, task.id), class: "delete_task", remote: true, method: :delete, data: { confirm: 'Are you sure?'} do
            i.fa.fa-trash
  - else
    .task class="completed" id="#{task.id}"
      .checkbox
        == check_box_tag("data", value = "#{task.project_id}", checked = true, class: 'task-check', id: task.id)
      .info
        - if task.deadline.nil?
          == task.name
        - else
          == task.name
          span #{task.deadline.strftime('%a, %m/%d/%y')}
      .options          
        == link_to project_task_path(task.project_id, task.id), class: "delete_task", remote: true, method: :delete, data: { confirm: 'Are you sure?'} do
            i.fa.fa-trash

app/views/tasks/change_position.js.erb
var project = $("<%= j (render @project) %>");
$('.project#' + project[0].id).replaceWith(project);

app/views/tasks/completed.js.erb
var project = $("<%= j (render @project) %>");
$('.project#' + project[0].id).replaceWith(project);

app/views/tasks/create.js.erb
var task = $("<%= escape_javascript(render @task) %>");

function getPostionForNewTask(form) {
if (form.parents('.project').find('.tasks').find('.task').size() == 0) {
  task.appendTo(form.parents('.project').find('.tasks'));
} else if (form.parents('.project').find('.tasks').find('.task.active').size() > 0) {
  form.parents('.project').find('.tasks').find('.task.active').last().after(task);
} else if (form.parents('.project').find('.tasks').find('.task.active').size() == 0 && form.parents('.project').find('.tasks').find('.task.completed').size() > 0) {
  form.parents('.project').find('.tasks').find('.task.completed').first().before(task);
  }
}

$("form#new_task").on("ajax:complete", function(event,xhr,status){
  this.reset();
  var form = $(event.currentTarget);
  getPostionForNewTask(form);
});

app/views/tasks/destroy.js.erb
$(".delete_task").on("ajax:complete", function(event,xhr,status){
  var task = $(event.currentTarget);
  task.parents('.task').remove();
});

app/views/tasks/edit.js.erb
$('<%= j render "tasks/edit" %>').modal().on('shown.bs.modal', function (e) {
  initDatepicker();
});

    // Task name and deadline validation
    $(document).on("ajax:error", function(e, data, status, xhr) {
      return $('form.edit_task').render_form_errors('task', data.responseJSON);
    });

    $.fn.render_form_errors = function(model_name, errors) {
      var form;
      form = this;
      this.clear_form_errors();
      return $.each(errors, function(field, messages) {
        var input;
        input = form.find('input').filter(function() {
          var name;
          name = $(this).attr('name');
          if (name) {
            return name.match(new RegExp(model_name + '\\[' + field + '\\(?'));
          }
        });
        input.closest('.form-group').addClass('has-error');
        return input.after('<span class="help-block">' + $.map(messages, function(m) {
          return m.charAt(0).toUpperCase() + m.slice(1);
        }).join('<br />') + '</span>');
      });
    };

    $.fn.clear_form_errors = function() {
      this.find('.form-group').removeClass('has-error');
      return this.find('span.help-block').remove();
    };

    $.fn.clear_form_fields = function() {
      return this.find(':input', 'form.edit_task').not(':button, :submit, :reset, :hidden').val('').removeAttr('checked').removeAttr('selected');
    };

app/views/tasks/update.js.erb
var task = $("<%= escape_javascript(render @task) %>");
$('.modal#edit_task').modal('hide').remove();
$('.modal-backdrop.fade.in').remove();
$('.task#' + task[0].id).replaceWith(task);

app/views/temp/create.js.erb
$('<%= j return root_path  %>')

app/views/welcome/index.slim
- if user_signed_in?
  == "Hello, #{current_user.email.split('@').first}"
  == link_to "Log out", destroy_user_session_path, :method => :delete
- else 
  == link_to "Sign in", "#sign_in", "data-toggle" => "modal", :class => 'btn btn-small'
  == link_to "Sign up", "#sign_up", "data-toggle" => "modal", :class => 'btn btn-small'
  == render 'shared/sign_in'
  == render 'shared/sign_up'

h1
  | SIMPLE TODO LIST

- if user_signed_in? 
  h2 Projects of #{current_user.email.split('@').first}
  
  - current_user.projects.order(created_at: :desc).each do |project|
    == render partial: 'projects/project', locals: {project: project}
          
  div class="links"
    == link_to "New Project", new_project_path, :remote => true, class: "btn btn-primary btn-lg"
  
- else 
  h2 Please #{link_to "sign in", "#sign_in", "data-toggle" => "modal", remote: true} or #{link_to "sign up", "#sign_up", "data-toggle" => "modal", remote: true}